\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Homework for Statistical Rethinking},
            pdfauthor={Kristoffer Klevjer},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother

\title{Homework for Statistical Rethinking}
\providecommand{\subtitle}[1]{}
\subtitle{UiT, Spring 2020}
\author{Kristoffer Klevjer}
\date{Current / knitted date: 2020-02-19}

\begin{document}
\maketitle

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{precursers}{%
\subsubsection{Precursers}\label{precursers}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Install (R)Stan. Go to \url{mc-stan.org}, or
  \href{https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started}{directly
  here} for RStan, follow all instructions including ``Loading the
  package''. PS: I had a lot of problems the first time, as I didn't
  have R v3.4.0 or later and/or RStudio v1.2.x or later.
\item
  Install the following packages: install.packages(c(``coda'',
  ``mvtnorm'', ``devtools'', ``loo''))
\item
  Load devtools: library(devtools)
\item
  Install the rethinking package:
  devtools::install\_github(``rmcelreath/rethinking'',
  ref=``Experimental'')
\item
  Pray that you didn't get any breaking-worthy errors, I got an error in
  the rethinking package related to serialized objects, however as this
  package is solely for learning, and not using Rstan, I'll take my
  chances.
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{week-one}{%
\subsection{Week One}\label{week-one}}

Overall: We are tossing a small globe around the room, and record
whether our right index finger lands on Water or Land when catching it.
Assuming the globe is a fair representation of Earth, we can use the
data we obtain to estimate the proportion of water to land on the
Earth's surface.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{task-1}{%
\subsubsection{Task 1}\label{task-1}}

Suppose the globe tossing data had turned out to be 8 water in 15
tosses. Construct the posterior distribution, using grid approximation.
Use the same flat prior as before.

\hypertarget{task-1---my-solution}{%
\subsubsection{Task 1 - My solution}\label{task-1---my-solution}}

In this task, we assume that we have no prior knowledge about the
Earth's proportion of water to land, i.e., we have a flat prior, with
all values being equally likely.

In this task, we can use grid approximation (fine grid instead of
integrals, often computationally intensive with increased amounts of
data/complexity).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p_grid1 <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from =} \DecValTok{0}\NormalTok{, }\DataTypeTok{to =} \DecValTok{1}\NormalTok{, }\DataTypeTok{length =} \DecValTok{1000}\NormalTok{) }\CommentTok{#grid of 1000}
\NormalTok{prob_p1 <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1000}\NormalTok{) }\CommentTok{#flat prior}
\NormalTok{prob_data1 <-}\StringTok{ }\KeywordTok{dbinom}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DataTypeTok{size =} \DecValTok{15}\NormalTok{, }\DataTypeTok{prob =}\NormalTok{ p_grid1)}
\NormalTok{posterior1 <-}\StringTok{ }\NormalTok{prob_data1 }\OperatorTok{*}\StringTok{ }\NormalTok{prob_p1 }\CommentTok{# taking the prior into account, not needed in this example}
\NormalTok{posteriornorm1 <-}\StringTok{ }\NormalTok{posterior1 }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(posterior1) }\CommentTok{#normalizing}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\NormalTok{samples1 <-}\StringTok{ }\KeywordTok{sample}\NormalTok{(p_grid1, }\DataTypeTok{prob =}\NormalTok{ posteriornorm1, }\DataTypeTok{size =} \DecValTok{1000}\NormalTok{, }\DataTypeTok{replace =} \OtherTok{TRUE}\NormalTok{)}
\KeywordTok{mean}\NormalTok{(samples1) }\CommentTok{#point estimate of the true proportion of water}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5214925
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{quantile}\NormalTok{(samples1, }\DataTypeTok{probs =} \KeywordTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.95}\NormalTok{)) }\CommentTok{#95% CI}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        5%       95% 
## 0.3201702 0.7087588
\end{verbatim}

In short, given the prior and the observed data, our best estimate for
the true proportion of water to land is \texttt{0.5214925} (95\%CI:
\texttt{0.3201702} to \texttt{0.7087588}).

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{task-2}{%
\subsubsection{Task 2}\label{task-2}}

Start over in \textbf{1}, but now use a prior that is zero below
\emph{p} = 0.5. This corresponds to prior information that a majority of
the Earth's surface is water. What difference does the better prior
make? If it helps, compare posterior distributions (using both priors)
to the true value \emph{p} = 0.7.

\hypertarget{task-2---my-solution}{%
\subsubsection{Task 2 - My solution}\label{task-2---my-solution}}

We can use the same code as above, only we adjust the prior probability.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p_grid2 <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from =} \DecValTok{0}\NormalTok{, }\DataTypeTok{to =} \DecValTok{1}\NormalTok{, }\DataTypeTok{length =} \DecValTok{1000}\NormalTok{) }\CommentTok{#grid of 1000}
\NormalTok{prob_p2 <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{500}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{500}\NormalTok{)) }\CommentTok{#new prior}
\NormalTok{prob_data2 <-}\StringTok{ }\KeywordTok{dbinom}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DataTypeTok{size =} \DecValTok{15}\NormalTok{, }\DataTypeTok{prob =}\NormalTok{ p_grid2)}
\NormalTok{posterior2 <-}\StringTok{ }\NormalTok{prob_data2 }\OperatorTok{*}\StringTok{ }\NormalTok{prob_p2 }\CommentTok{# taking the prior into account, not needed in this example}
\NormalTok{posteriornorm2 <-}\StringTok{ }\NormalTok{posterior2 }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(posterior2) }\CommentTok{#normalizing}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\NormalTok{samples2 <-}\StringTok{ }\KeywordTok{sample}\NormalTok{(p_grid2, }\DataTypeTok{prob =}\NormalTok{ posteriornorm2, }\DataTypeTok{size =} \DecValTok{1000}\NormalTok{, }\DataTypeTok{replace =} \OtherTok{TRUE}\NormalTok{)}
\KeywordTok{mean}\NormalTok{(samples2) }\CommentTok{#point estimate of the true proportion of water}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6035395
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{quantile}\NormalTok{(samples2, }\DataTypeTok{probs =} \KeywordTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.95}\NormalTok{)) }\CommentTok{#95% CI}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        5%       95% 
## 0.5095095 0.7347347
\end{verbatim}

In short, given the \emph{new} prior and the observed data, our best
estimate for the true proportion of water to land is \texttt{0.6035395}
(95\%CI: \texttt{0.5095095} to \texttt{0.7347347}). As we can see, this
brings us close to the true proportion of \(\sim 0.7\), as well as
provides a narrower intervall.

The difference this different prior made can be easier to see visually:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(samples1), }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{), }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{6}\NormalTok{), }\DataTypeTok{col=}\StringTok{"blue"}\NormalTok{, }\DataTypeTok{main=}\StringTok{"Density distributions for estimates of water proportion"}\NormalTok{, }\DataTypeTok{sub=}\StringTok{"(1. in blue, 2. in red, and the correct proportion as a purple line)"}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{"Proportion of water"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Density"}\NormalTok{) }\CommentTok{#calling the first plot as well as setting label and x/y limits}
\KeywordTok{lines}\NormalTok{(}\KeywordTok{density}\NormalTok{(samples2), }\DataTypeTok{col=}\StringTok{"red"}\NormalTok{) }\CommentTok{#calling the second plot}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{v=}\FloatTok{0.7}\NormalTok{, }\DataTypeTok{col=}\StringTok{"purple"}\NormalTok{) }\CommentTok{#calling the line for the true proportion}
\end{Highlighting}
\end{Shaded}

\includegraphics{KnittedRMarkDown_files/figure-latex/unnamed-chunk-3-1.pdf}

In summary: The new prior gives us a model with more AUC close to the
real proportion, and a ``peakyer'' distribution. However as our (highly)
limited sample-size was randomly skewed away from the real proportion,
neither of these two models are very good at capturing the true
proportion.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{task-3}{%
\subsubsection{Task 3}\label{task-3}}

This problem is more open-ended than the others. Feel free to
collaborate on the solution. Suppose you want to estimate the Earth's
proportion of water very precisely. Specifically, you want the 99\%
percentile interval of the posterior distribution of \emph{p} to be only
0.05 wide. This means the distance between the upper and lower bound of
the interval should be 0.05. How many times will you have to toss the
globe to do this? I won't require a precise answer. I'm honestly more
interested in your approach.

\hypertarget{task-3---my-solution}{%
\subsubsection{Task 3 - My solution}\label{task-3---my-solution}}

Assuming the toy globe have an accurate representation, and indendant
tossing trials, which will eventually reach the true proportion, we can
make a repeat loop that stops at the correct/needed amounts of throws to
get a 99\%CI of less than 0.05.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{kast <-}\StringTok{ }\DecValTok{1}
\ControlFlowTok{repeat}\NormalTok{ \{}
\NormalTok{kast <-}\StringTok{ }\NormalTok{kast}\OperatorTok{+}\DecValTok{1}
\NormalTok{vann <-}\StringTok{ }\DecValTok{7} \OperatorTok{*}\StringTok{ }\NormalTok{kast}
\NormalTok{total <-}\StringTok{ }\NormalTok{vann}\OperatorTok{/}\FloatTok{0.7}
\NormalTok{p_grid3 <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DataTypeTok{from =} \DecValTok{0}\NormalTok{, }\DataTypeTok{to =} \DecValTok{1}\NormalTok{, }\DataTypeTok{length =}\NormalTok{ total)}
\NormalTok{prob_data3 <-}\StringTok{ }\KeywordTok{dbinom}\NormalTok{(vann, }\DataTypeTok{size =}\NormalTok{ total, }\DataTypeTok{prob=}\NormalTok{ p_grid3)}
\NormalTok{posterior3 <-}\StringTok{ }\NormalTok{prob_data3}
\NormalTok{posteriornorm3 <-}\StringTok{ }\NormalTok{posterior3 }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(posterior3)}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\NormalTok{samples3 <-}\StringTok{ }\KeywordTok{sample}\NormalTok{(p_grid3, }\DataTypeTok{prob =}\NormalTok{ posteriornorm3, }\DataTypeTok{size =}\NormalTok{ total, }\DataTypeTok{replace =} \OtherTok{TRUE}\NormalTok{)}
\KeywordTok{mean}\NormalTok{(samples3)}
\KeywordTok{quantile}\NormalTok{(samples3, }\DataTypeTok{probs=} \KeywordTok{c}\NormalTok{(}\FloatTok{0.005}\NormalTok{, }\FloatTok{0.995}\NormalTok{))}
\NormalTok{sjekk <-}\StringTok{ }\KeywordTok{quantile}\NormalTok{(samples3, }\DataTypeTok{probs =} \FloatTok{0.995}\NormalTok{) }\OperatorTok{-}\StringTok{ }\KeywordTok{quantile}\NormalTok{(samples3, }\DataTypeTok{probs=}\FloatTok{0.005}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\KeywordTok{quantile}\NormalTok{(samples3, }\DataTypeTok{probs =} \FloatTok{0.995}\NormalTok{) }\OperatorTok{-}\StringTok{ }\KeywordTok{quantile}\NormalTok{(samples3, }\DataTypeTok{probs=}\FloatTok{0.005}\NormalTok{) }\OperatorTok{<}\StringTok{ }\FloatTok{0.05}\NormalTok{)\{}
  \ControlFlowTok{break}
\NormalTok{\}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

This ``brute-force'' method gives us the approximate needed numbers of
throws:

\begin{verbatim}
## [1] 2410
\end{verbatim}

And we can put this into our graph:

\includegraphics{KnittedRMarkDown_files/figure-latex/unnamed-chunk-6-1.pdf}

For fun, we can add a final graph, showing the same model, but with
\(\sim\) half of the number of throws from above.

\includegraphics{KnittedRMarkDown_files/figure-latex/unnamed-chunk-8-1.pdf}

As we can see, the doubleing of throws does not do a whole lot for the
model, this is because we enter an area of dimishing returnes, where
each new case gets a smaller and smaller impact, due to the large number
of previous trials (might not be the case in every setup).

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{week-one-1}{%
\subsection{Week One}\label{week-one-1}}

\end{document}
